-- DROP DATABASE retrohouse;
-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 12:55:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema retrohouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema retrohouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retrohouse` DEFAULT CHARACTER SET utf8 ;
USE `retrohouse` ;

-- -----------------------------------------------------
-- Table `retrohouse`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrohouse`.`rol` ;

CREATE TABLE IF NOT EXISTS `retrohouse`.`rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retrohouse`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrohouse`.`usuario` ;

CREATE TABLE IF NOT EXISTS `retrohouse`.`usuario` (
  `documentoCliente` VARCHAR(15) NOT NULL,
  `nombreCompleto` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `celular` VARCHAR(10) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `idRol` INT NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `imagenPerfil` LONGTEXT,
  `estado` INT NOT NULL,
  PRIMARY KEY (`documentoCliente`),
  INDEX `fk_Usuarios_Roles_idx` (`idRol` ASC),
  CONSTRAINT `fk_Usuarios_Roles`
    FOREIGN KEY (`idRol`)
    REFERENCES `retrohouse`.`rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retrohouse`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrohouse`.`categoria` ;

CREATE TABLE IF NOT EXISTS `retrohouse`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retrohouse`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrohouse`.`producto` ;

CREATE TABLE IF NOT EXISTS `retrohouse`.`producto` (
  `idProducto` INT AUTO_INCREMENT NOT NULL,
  `nombreProducto` VARCHAR(100) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `imagen` LONGTEXT NOT NULL,
  `musica` LONGTEXT NOT NULL,
  `idCategoria` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Categoria1_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `retrohouse`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retrohouse`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrohouse`.`venta` ;

CREATE TABLE IF NOT EXISTS `retrohouse`.`venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `total` DOUBLE NOT NULL,
  `documentoUsuario` VARCHAR(15) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Usuarios1_idx` (`documentoUsuario` ASC),
  CONSTRAINT `fk_Venta_Usuarios1`
    FOREIGN KEY (`documentoUsuario`)
    REFERENCES `retrohouse`.`usuario` (`documentoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retrohouse`.`DetalleVenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrohouse`.`detalleVenta` ;

CREATE TABLE IF NOT EXISTS `retrohouse`.`detalleventa` (
  `idDetalleVenta` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precioUnitario` DOUBLE NOT NULL,
  `idProducto` INT NOT NULL,
  `idVenta` INT NOT NULL,
  PRIMARY KEY (`idDetalleVenta`),
  INDEX `fk_DetalleVenta_Producto1_idx` (`idProducto` ASC),
  INDEX `fk_DetalleVenta_Venta1_idx` (`idVenta` ASC),
  CONSTRAINT `fk_DetalleVenta_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `retrohouse`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleVenta_Venta1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `retrohouse`.`venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- ------------------------------------------------------
-- Table `retrohouse`.`Proveedor`
-- ------------------------------------------------------
DROP TABLE IF EXISTS `retrohouse`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `retrohouse`.`proveedor`(
	`idProveedor` INT NOT NULL AUTO_INCREMENT,
    `nombreProveedor` VARCHAR(50) NOT NULL,
    `correoProveedor` VARCHAR(100) NOT NULL,
    `telefonoProveedor` VARCHAR(15) NOT NULL,
    `estado` INT NOT NULL,
    PRIMARY KEY (`idProveedor`)
) 
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `retrohouse`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrohouse`.`compra`;

CREATE TABLE IF NOT EXISTS `retrohouse`.`compra`(
	`idCompra` INT NOT NULL AUTO_INCREMENT,
    `fechaCompra` DATETIME NOT NULL,
    `totalCompra` DOUBLE NOT NULL,
    `idProveedor` INT NOT NULL,
    PRIMARY KEY (`idCompra`),
    INDEX `fk_Proveedor_Proveedor1_idx` (`idProveedor` ASC),
    CONSTRAINT `fk_Proveedor_Proveedor1`
		FOREIGN KEY (`idProveedor`)
        REFERENCES `retrohouse`.`proveedor` (`idProveedor`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `retrohouse`.`DetalleCompra`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `retrohouse`.`detallecompra`;

CREATE TABLE IF NOT EXISTS `retrohouse`.`detallecompra`(
	`idDetalleCompra` INT NOT NULL AUTO_INCREMENT,
    `cantidad` INT NOT NULL,
    `precioUnitario`DOUBLE NOT NULL,
    `idCompra` INT NOT NULL,
    `idProducto` INT NOT NULL,
    PRIMARY KEY (`idDetalleCompra`),
    INDEX `fk_Compra_Compra1_idx` (`idCompra` ASC),
    INDEX `fk_Producto_Producto1_idx` (`idProducto` ASC),
    CONSTRAINT `fk_Compra_Compra1`
		FOREIGN KEY (`idCompra`)
        REFERENCES `retrohouse`.`compra` (`idCompra`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
	CONSTRAINT `fk_Producto_Producto1`
		FOREIGN KEY (`idProducto`)
        REFERENCES `retrohouse`.`producto` (`idProducto`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `retrohouse`.`EstadoCarrito`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `retrohouse`.`estadoCarrito`;

CREATE TABLE IF NOT EXISTS `retrohouse`.`estadoCarrito` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(25) NOT NULL,
  PRIMARY KEY(`id`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `retrohouse`.`Carrito`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `retrohouse`.`carrito`;

CREATE TABLE IF NOT EXISTS `retrohouse`.`carrito` (
	`id` INT AUTO_INCREMENT NOT NULL,
	`cantidad` INT NOT NULL,
	`idUsuario` VARCHAR(15) NOT NULL,
	`idProducto` INT NOT NULL,
	`idEstado` INT NOT NULL,
	PRIMARY KEY (`id`),
	INDEX `fk_Usuario_Usuario2_idx` (`idUsuario` ASC),
	INDEX `fk_Producto_Producto2_idx` (`idProducto` ASC),
	INDEX `fk_Estado_Estado2_idx`(`idEstado` ASC),
	CONSTRAINT `fk_Usuario_Usuario2`
		FOREIGN KEY (`idUsuario`)
		REFERENCES `retrohouse`.`usuario` (`documentoCliente`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	CONSTRAINT `fk_Producto_Producto2`
		FOREIGN KEY (`idProducto`)
        REFERENCES `retrohouse`.`producto` (`idProducto`)
        ON DELETE NO ACTION 
        ON UPDATE NO ACTION,
	CONSTRAINT `fk_Estado_Estado2`
		FOREIGN KEY (`idEstado`)
        REFERENCES `retrohouse`.`estadoCarrito`(`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `retrohouse`.`EstadoVenta`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `retrohouse`.`estadoVenta`;

CREATE TABLE IF NOT EXISTS `retrohouse`.`estadoVenta` (
  `id` INT NOT NULL,
  `descripción` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
